'use strict'

const fs = require('node:fs')
const path = require('node:path')

const { agentDir } = require('./runtimeEnv')
const { instancePromptRelativePath, memoryRelativePath } = require('./personalityText')
const { tomlString } = require('./toml')

/// Rendered fresh on every start. Keys never land here — they go to the child
/// process as environment variables instead, so a config file someone pastes
/// into an issue carries no credential.
function renderConfigToml(s) {
  const lines = [
    '# Generated by the OpenMMO agent desktop app. Edits are overwritten on',
    '# every start; change the values in the app instead.',
    '',
    `server = ${tomlString(s.server)}`,
    `terrain = ${tomlString(s.terrain)}`,
    'terrain_cache = "data/cache/height"',
    `watch_port = ${Number(s.watchPort) || 0}`,
    `max_concurrent = ${Number(s.maxConcurrent) || 2}`,
    `request_timeout_secs = ${Number(s.requestTimeoutSecs) || 120}`,
    '',
    '[auth]',
    `mode = ${tomlString(s.authMode)}`,
  ]
  if (s.authMode === 'google') {
    // Must match whatever client_id the pre-flight session (characterSession.js)
    // signed in as: agent-client only reuses the cached refresh token when the
    // cache's client_id equals this one (google_auth.rs), so a mismatch here
    // silently throws away the sign-in Login already did and re-prompts.
    lines.push(`client_id = ${tomlString(s.googleClientId)}`)
    if (s.googleClientSecret) lines.push(`client_secret = ${tomlString(s.googleClientSecret)}`)
  }

  lines.push('', '[claude]', `model = ${tomlString(s.models.claude)}`)
  lines.push('', '[codex]', `model = ${tomlString(s.models.codex)}`)
  lines.push(
    '',
    '[openrouter]',
    `model = ${tomlString(s.models.openrouter)}`,
    `max_tokens = ${Number(s.maxTokens) || 1024}`,
    `temperature = ${Number(s.temperature)}`,
  )
  lines.push(
    '',
    '[openai]',
    `base_url = ${tomlString(s.openaiBaseUrl)}`,
    `model = ${tomlString(s.models.openai)}`,
    `max_tokens = ${Number(s.maxTokens) || 1024}`,
    `temperature = ${Number(s.temperature)}`,
    `reasoning_effort = ${tomlString(s.reasoningEffort)}`,
    // Whole numbers only, floored at openai.rs's MIN_MAX_MESSAGES: the field
    // is a `usize`, so a fraction imported from a hand-edited config fails to
    // deserialize and the agent never starts, and below 3 its trim underflows.
    `max_messages = ${Math.max(Math.round(Number(s.maxMessages)) || 41, 3)}`,
  )

  lines.push('', '[[npcs]]', `llm = ${tomlString(s.llm)}`)
  if (s.authMode !== 'google') lines.push(`account = ${tomlString(s.npcAccount)}`)
  // Google auth resolves the account from the id_token alone and hands back
  // its whole character list — agent-client enters the first one if no name
  // is given, or creates one if the name doesn't match. A name is only
  // needed to pick among several characters or to create a new one.
  if (s.characterName) lines.push(`character_name = ${tomlString(s.characterName)}`)
  lines.push(
    `character_class = ${tomlString(s.characterClass)}`,
    `gender = ${tomlString(s.gender)}`,
    `min_interval_secs = ${Number(s.minIntervalSecs) || 5}`,
    `idle_interval_secs = ${Number(s.idleIntervalSecs) || 15}`,
    `always_active = ${s.alwaysActive ? 'true' : 'false'}`,
    // Without this the `memory_update` the model writes every turn is thrown
    // away, and the agent relearns the same town from scratch on each restart.
    // Keyed per character (like instance_prompt below) so switching characters
    // doesn't mix one character's memories into another's prompt.
    `memory_file = ${tomlString(s.characterName ? memoryRelativePath(s.characterName) : 'data/memory.txt')}`,
  )
  // agent-client hard-errors on a configured prompt file that doesn't exist
  // (load_system_prompt), unlike memory_file's own missing-file tolerance —
  // so this is only ever written once ensureInstancePrompt() below has
  // guaranteed the file is actually there.
  if (s.characterName) lines.push(`instance_prompt = ${tomlString(instancePromptRelativePath(s.characterName))}`)
  lines.push('')
  return lines.join('\n')
}

function writeConfig(settings) {
  const dir = path.join(agentDir(), 'data')
  fs.mkdirSync(dir, { recursive: true })
  const file = path.join(dir, 'config.toml')
  const backup = `${file}.bak`
  if (fs.existsSync(file) && !fs.existsSync(backup)) fs.copyFileSync(file, backup)
  fs.writeFileSync(file, renderConfigToml(settings))
  return file
}

module.exports = {
  renderConfigToml,
  writeConfig,
}
